name: Run Cypress Tests

# Evento para rodar os testes no push e merge para a branch 'main'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
    contents: write

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - name: Step 1 - Checkout repository
        uses: actions/checkout@v4

      # Configuração do Node.js (usando versão 16.x)
      - name: Step 2 - Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Instalação de dependências do projeto
      - name: Step 3 - Instalar dependencias
        run: npm install --verbose

      # Rodando os testes com o Cypress
      - name: Step 4 - Execucao dos testes com cypress
        run: npm run allure:chro
        continue-on-error: true

      # Salvar os relatórios de testes como artefato
      - name: Step 5 - gerar allure report
        run: npm run allure:ci

      # Publicar resultado como comentário no pull request (opcional)
      - name: Step 6 - Upload Allure report
        uses: actions/upload-artifact@v3
        with:
          name: report allure
          path: allure-report

      - name: Step 7 - publish report
        uses: peaceiris/actions-gh-pages@v4
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_branch: report_page_TAYA_cypress
           publish_dir: allure-report